---
name: Build ArchLinux zfs iso with LTS-Kernel and DKMS Package
on:
  schedule:  # arch relases are published first day of the month
    - cron: '50 23 1 * *'
  workflow_dispatch:
  pull_request:
    types:
      - closed
  push:

jobs:
  Update-AppImage:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Git clone from AUR
        run: git clone https://aur.archlinux.org/nextcloud-client-appimage-daily.git
      - name: Checkout codebase
        action: actions/checkout@v3
          # TODO: Build automatically inside an ArchLinux Chroot
      - name: Install all latest dependencies in container
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm zlib curl p7zip hicolor-icon-theme wget bash base-devel 
      - name: Chmod update script
        run: "chmod +x ./update.sh && ./update.sh"
      # INSERT step to setup git config from ENV variable containing secrets????
      # TODO: Find if that's a good solution ^ or to avoid in terms of security
      # Read a lot of documentation and blogs...
      - name: Build latest update from upstream
        run: |
          chmod +x ./update.sh
          ls 
          bash ./update.sh --verbose
