name: Build Nextcloud from upstream daily and push to AUR latest release

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

  workflow_dispatch:

jobs:
  Update-AppImage:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
          # TODO: Build automatically inside an ArchLinux Chroot
      - name: Install all latest dependencies in container
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm zlib curl p7zip hicolor-icon-theme wget bash base-devel git fuse2 pacman-contrib libx11 xorg-server lib32-fontconfig fontconfig
      - name: Git clone from AUR
        run: git clone https://aur.archlinux.org/nextcloud-client-appimage-daily.git
      # INSERT step to setup git config from ENV variable containing secrets????
      # TODO: Find if that's a good solution ^ or to avoid in terms of security
      # Read a lot of documentation and blogs...
      - name: Build latest update from upstream
        run: |
          chmod +x ./update.sh
          ls 
          bash ./update.sh
